### ISSUE TITLE
Change License

### ISSUE THREAD

**Issue by kamranzafar** [nociar/jpa-cloner#18]
Hi, thanks for the useful library, is it possible for you to change the license to something more permissive like Apache License??

**Comment by nociar** [comment]
Hello, do you have some doubt about using this library in your code? For example embedding of the JAR artefact?

**Comment by nociar** [comment]
Hello again, I will look at the Apache License 2.0 and LGPL. Please note that you can link/embed the JPA cloner library in your project. I do not require to release your proprietary projects as GPL.

**Comment by kamranzafar** [comment]
Thanks for getting back, yes it would be great if you could release jpa-cloner under either Apache license or LGPL. I don't have any issues using GPL for an open source project but this license becomes a problem for propriety code. thanks again.

**Comment by NagyGa1** [comment]
Hi,
Thanks for the great package.
Just dropping a note that this is an issue for the firm I am working for as well.

**Comment by nociar** [comment]
The license is changed to Apache License, Version 2.0
...will be available via Maven Repo later...
