### ISSUE TITLE
Foreign Key Validation Exception when cloning and saving parent-child one-to-many relationship.

### ISSUE THREAD

**Issue by codebusta** [nociar/jpa-cloner#21]
I have the following domain objects: Promotion and PromotionItem, one-to-many relationship.

``` Java
@Entity
@Table(schema = "public", name = Tables.PROMOTION)
public class Promotion extends DataEntity implements HasTrackDomain {
    @OneToMany(mappedBy = "promotionId", cascade = CascadeType.ALL)
    private List<PromotionItem> promotionItems = new ArrayList();
}


@Entity
@Table(schema = "public", name = Tables.PROMOTION_ITEM)
public class PromotionItem extends DataEntity {
     @NotNull
    @Column(nullable = false)
    private long promotionId;
    @ManyToOne(cascade = {CascadeType.PERSIST}, fetch = FetchType.LAZY)
    @JoinColumn(name = "promotionId", updatable = false, insertable = false)
    private Promotion promotion;
}
```

I cloned Promotion as follows:

``` Java
Promotion p = entityManager.find(Promotion.class, promotion.getId());
PropertyFilter cloneFilter = new PropertyFilter() {
            public boolean test(Object entity, String property) {
                return !"id".equals(property) && !"promotionId".equals(property);
            }
};
Promotion clonedPromotion = JpaCloner.clone(p, cloneFilter, "promotionItems");
entityManager.persist(clonedPromotion);
```

The following exception is thrown:

org.hibernate.exception.ConstraintViolationException: ERROR: insert or update on table "promotion_item" violates foreign key constraint "fk29f2a52f6fc76efb"
  Detail: Key (promotionid)=(0) is not present in table "promotion".

For some reason, at the time of persist, the id of the newly cloned promotion is not being set to the promotion_item's promotionId field. Can you provide solution how to fix this? Thank you in advance.

**Comment by nociar** [comment]
Hello, this seems to be a problem of your ORM mapping, not the JPA Cloner issue. The JPA cloner correctly clones id and promotionId property - both are set to zero or NULL after cloning. Hibernate then correctly issues the exception during the persist() operation. The PromotionItem class should not have the promotionId field and the mappedBy attribute should be different. Correct ORM mapping is:

``` Java
@Entity
@Table(schema = "public", name = Tables.PROMOTION)
public class Promotion extends DataEntity implements HasTrackDomain {
    @OneToMany(mappedBy = "promotion", cascade = CascadeType.ALL)
    private List<PromotionItem> promotionItems = new ArrayList();
}

@Entity
@Table(schema = "public", name = Tables.PROMOTION_ITEM)
public class PromotionItem extends DataEntity {
    @ManyToOne(cascade = {CascadeType.PERSIST}, fetch = FetchType.LAZY)
    @JoinColumn(name = "promotionId", updatable = true, insertable = true)
    private Promotion promotion;
}
```

**Comment by nociar** [comment]
Hello, are the any news with this issue? Did you try to change the ORM mapping?
