### ISSUE TITLE
generic deep clone?

### ISSUE THREAD

**Issue by avishaybennatan** [nociar/jpa-cloner#22]
Hi ,
i am currently using the cloner to clone jpa entities with different hierarchy
aka:
a containing a list of b and b containing a list of c (all lists are lazy)
and another entity of d containing list of e 
i would like to deep clone a without specifying the depth of cloning (aka without "_+._+"),
is this possible?

**Comment by nociar** [comment]
Hello, the JPA cloner contains the wildcard " \* " and repetition " + ". So, if you are 100% sure that you want to clone everything, just use the following selector:

``` java
Entity clone = JpaCloner.clone(original, "*+");
```

But be careful - it will copy all related objects recursively... The object graph could be sometimes huge :-)
