### ISSUE TITLE
I'm getting "argument type mismatch"

### ISSUE THREAD

**Issue by clopezuab** [nociar/jpa-cloner#24]
Hi, thanks for this library, it's what I need. 

I need to clone the whole graph, but I can't do it, I'm always getting the error:

`java.lang.RuntimeException: java.lang.IllegalArgumentException: argument type mismatch
    at sk.nociar.jpacloner.properties.MethodPropertyWriter.set(MethodPropertyWriter.java:19)
    at sk.nociar.jpacloner.JpaPropertyInfo.setValue(JpaPropertyInfo.java:95)
    at sk.nociar.jpacloner.JpaCloner.copyBasicProperties(JpaCloner.java:247)
    at sk.nociar.jpacloner.JpaCloner.clone(JpaCloner.java:92)
    at sk.nociar.jpacloner.JpaCloner.clone(JpaCloner.java:182)
`

My code is:

`GranjaManager original = em.find(GranjaManager.class, granjaManager.getId());
        PropertyFilter filter = PropertyFilters.getAnnotationFilter(Id.class, Transient.class);
        GranjaManager clone = JpaCloner.clone(original, filter, "*+");`

**Comment by nociar** [comment]
Hello, this seems that a setter has a different argument than a field or a getter. Could you please try to debug and inspect the exception?

**Comment by clopezuab** [comment]
Ok! Thanks Miroslav, Yeah, it was that! 

By the way, great library man, love it!

**Comment by nociar** [comment]
Hello, I am glad to hear that ;-) May be I should add a check for this issue and raise a more descriptive exception...

**Comment by clopezuab** [comment]
Yeah, it would be easier to know what's happening.
